In [1]:
import cv2
import numpy as np
from PIL import Image

In [2]:
def sobel_X():
    kernel = np.array([[-1, 0, 1], [-2, 0, 2], [-1, 0, 1]])
    return kernel

In [3]:
def sobel_Y():
    kernel = np.array([[1, 2, 1], [0, 0, 0], [-1, -2, -1]])
    return kernel

In [4]:
def prewitt_X():
    kernel = np.array([[-1, 0, 1], [-1, 0, 1], [-1, 0, 1]])
    return kernel

In [5]:
def prewitt_Y():
    kernel = np.array([[1, 1, 1], [0, 0, 0], [-1, -1, -1]])
    return kernel

In [6]:
def gradient(img, size, mask):
    if len(img.shape) == 3: 
        H, W, C = img.shape
    else: 
        img = np.expand_dims(img, axis=-1)
        H, W, C = img.shape

    pad = size // 2
    out = np.zeros((H + pad * 2, W + pad * 2, C), dtype=np.float)
    out[pad: pad + H, pad: pad + W] = img.copy().astype(np.float)

    print(mask)

    tmp = out.copy()
    
    for i in range(H): 
        for j in range(W): 
            for k in range(C): 
                out[pad + i, pad + j, k] = np.sum(mask * tmp[i: i + size, j: j + size, k]) 
    out = np.clip(out, 0, 255) 
    out = out[pad: pad + H, pad: pad + W].astype(np.uint8) 
    
    return out

In [ ]:
img = cv2.imread('Fig0327(a)(tungsten_original).jpg') 

out_x = gradient(img, 3, sobel_X())
out_y = gradient(img, 3, sobel_Y())

merged = out_x+out_y

out_x2 = gradient(img, 3, prewitt_X())
out_y2 = gradient(img, 3, prewitt_Y())

merged2 = out_x2+out_y2

cv2.imshow("sobel", merged) 
cv2.imshow("prewitt", merged2) 
cv2.waitKey(0) 
cv2.destroyAllWindows()

[[-1  0  1]
 [-2  0  2]
 [-1  0  1]]
[[ 1  2  1]
 [ 0  0  0]
 [-1 -2 -1]]
[[-1  0  1]
 [-1  0  1]
 [-1  0  1]]
[[ 1  1  1]
 [ 0  0  0]
 [-1 -1 -1]]
