In [6]:
import cv2
import numpy as np
from PIL import Image

In [7]:
def log_3x3():
    kernel = np.array([[1, 1, 1], [1, -8, 1], [1, 1, 1]])
    return kernel

In [8]:
def log_5x5():
    kernel = np.array([[0,0,1,0,0], [0,1,2,1,0], [1,2,-16,2,1], [0,1,2,1,0],[0,0,1,0,0]])
    return kernel

In [9]:
def LoG_filter(img, size, mask):
    if len(img.shape) == 3: 
        H, W, C = img.shape
    else: 
        img = np.expand_dims(img, axis=-1)
        H, W, C = img.shape

    pad = size // 2
    out = np.zeros((H + pad * 2, W + pad * 2, C), dtype=np.float)
    out[pad: pad + H, pad: pad + W] = img.copy().astype(np.float)

    print(mask)

    tmp = out.copy()
    
    for i in range(H): 
        for j in range(W): 
            for k in range(C): 
                out[pad + i, pad + j, k] = np.sum(mask * tmp[i: i + size, j: j + size, k]) 
    out = np.clip(out, 0, 255) 
    out = out[pad: pad + H, pad: pad + W].astype(np.uint8) 
    
    return out

In [10]:
img = cv2.imread('Fig0327(a)(tungsten_original).jpg') 

out1 = LoG_filter(img, 3, log_3x3())
out2 = LoG_filter(img, 5, log_5x5())

cv2.imshow("log_3x3", out1) 
cv2.imshow("log_5x5", out2) 
cv2.waitKey(0) 
cv2.destroyAllWindows()

[[ 1  1  1]
 [ 1 -8  1]
 [ 1  1  1]]
[[  0   0   1   0   0]
 [  0   1   2   1   0]
 [  1   2 -16   2   1]
 [  0   1   2   1   0]
 [  0   0   1   0   0]]
